### ISSUE TITLE
Could you add the southern part next to the teleport to the plugin aswell?

### ISSUE THREAD

**Issue by FreggleRS** [ArtsicleOfficial/Qolting#2]
![image](https://user-images.githubusercontent.com/96730409/184922672-1b28dcf7-bb23-4430-ad5c-ae6c561f3eb1.png)

**Comment by FreggleRS** [comment]
currently the area is not supported.

**Comment by ArtsicleOfficial** [comment]
The plugin was initially just made for me, and I don't play OSRS anymore, so I didn't care much to solve this exact problem, but:
In the latest update you'll be able to turn off the "Only inside Darkmeyer" option which will globally enable the plugin.
I didn't get around to adding that region (which would be a trivial `|| region_id == whatever_region_id_that_is`) but hopefully this option will work for you.

**Comment by ArtsicleOfficial** [comment]
Oh, it seems I actually patched this a day after the issue and didn’t mark this as closed?
It seems perhaps we do cover the southern region, after all.

https://github.com/runelite/plugin-hub/pull/3202

https://github.com/ArtsicleOfficial/Qolting/compare/83e95d2c2cc77c1d0eadefaa9ea8bbec62eef5b5...ArtsicleOfficial:deb12130b7acdda86a1628583bafcd176d5f90de

<img width="634" alt="image" src="https://github.com/ArtsicleOfficial/Qolting/assets/35227462/077b82a5-1321-40f6-a65d-8efcb5d1344b">
