### ISSUE TITLE
Bar display on bottom

### ISSUE THREAD

**Issue by ar1a** [ArtsicleOfficial/Qolting#4]
Would love for an option so flip the bar display to the bottom of the client

**Comment by ArtsicleOfficial** [comment]
Update will be out when the RuneLite team reviews it.
It will be off by default, and configured on in the settings.
Also, I made the bar outline color customizable (and "disabling" it is now setting its color opacity to 0)
![image](https://github.com/ArtsicleOfficial/Qolting/assets/35227462/d79f4b77-2fe3-4ae6-9258-60676fdc1a19)
![image](https://github.com/ArtsicleOfficial/Qolting/assets/35227462/2d8e6462-1592-4523-a82d-caae04bb6c8c)

**Comment by ArtsicleOfficial** [comment]
Track the update here: https://github.com/runelite/plugin-hub/pull/5752

**Comment by ar1a** [comment]
Thanks so much!
